FRAC_TRAIN = 0.05
BATCH_SIZE = 8
EPOCHS = 30
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 0
MILESTONES = [15, 22]
GAMMA = 0.1
SEED = 30
NUM_CLASSES = 6
SAMPLE_DURATION = 28  # Matches paper specifications for target datasets
MODEL_PATH = "resnet-34-kinetics-cpu.pth"
DATA_TYPE = "real_qiang"
SAVE_DIR = f"models/models_random_3_{DATA_TYPE}"
MODEL_NAME = f"resnet_{FRAC_TRAIN}.pth"
TRAIN_PATH = f"./data_split_qiang/train_real_split.csv"
VAL_PATH = f"./data_split_qiang/val_real_split.csv"
TEST_PATH = f"./data_split_qiang/val_real_split.csv"
DATASET = "experimental_data_qiang"
MEAN = 0
STD = 1
